/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.PDI;

/**
 *
 * @author XAV
 */
public class frameBienvenida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameBienvenida.class.getName());
    
    /**
     * Creates new form frameBienvenida
     */
    public frameBienvenida() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        jPanelContent = new javax.swing.JPanel();
        jPanelSpace7 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jPanelSpace6 = new javax.swing.JPanel();
        jPanelSeparador1 = new javax.swing.JPanel();
        jPanelSpace4 = new javax.swing.JPanel();
        jPanelDeveloper = new javax.swing.JPanel();
        jLabelDevLabel = new javax.swing.JLabel();
        jLabelStudentName = new javax.swing.JLabel();
        jLabelCareer = new javax.swing.JLabel();
        jPanelSpace8 = new javax.swing.JPanel();
        jPanelContentEmail = new javax.swing.JPanel();
        jPanelEmail = new javax.swing.JPanel();
        jLabelLinkEmail = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIconEmail = new javax.swing.JLabel();
        jPanelSpace2 = new javax.swing.JPanel();
        jPanelAsesor = new javax.swing.JPanel();
        jLabelAsesorLabel = new javax.swing.JLabel();
        jLabelStudentName1 = new javax.swing.JLabel();
        jPanelSpace1 = new javax.swing.JPanel();
        jButtonAcceso = new javax.swing.JButton();
        jPanelSpace9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 550));
        setMinimumSize(new java.awt.Dimension(420, 550));
        setPreferredSize(new java.awt.Dimension(450, 550));
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(10, 10, 10));
        panelBackground.setLayout(new java.awt.BorderLayout());

        jPanelContent.setBackground(new java.awt.Color(10, 10, 10));
        jPanelContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelContent.setLayout(new javax.swing.BoxLayout(jPanelContent, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelSpace7.setBackground(new java.awt.Color(10, 10, 10));

        javax.swing.GroupLayout jPanelSpace7Layout = new javax.swing.GroupLayout(jPanelSpace7);
        jPanelSpace7.setLayout(jPanelSpace7Layout);
        jPanelSpace7Layout.setHorizontalGroup(
            jPanelSpace7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelSpace7Layout.setVerticalGroup(
            jPanelSpace7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelSpace7);

        jPanelHeader.setBackground(new java.awt.Color(10, 10, 10));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(400, 60));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanelHeader.setLayout(new java.awt.BorderLayout());

        jLabelTitulo.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(185, 28, 28));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("PROCESADOR DE IMÁGENES");
        jPanelHeader.add(jLabelTitulo, java.awt.BorderLayout.CENTER);

        jLabelSubtitulo.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabelSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubtitulo.setText("PDI - 📷");
        jPanelHeader.add(jLabelSubtitulo, java.awt.BorderLayout.SOUTH);

        jPanelContent.add(jPanelHeader);

        jPanelSpace6.setBackground(new java.awt.Color(10, 10, 10));

        javax.swing.GroupLayout jPanelSpace6Layout = new javax.swing.GroupLayout(jPanelSpace6);
        jPanelSpace6.setLayout(jPanelSpace6Layout);
        jPanelSpace6Layout.setHorizontalGroup(
            jPanelSpace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelSpace6Layout.setVerticalGroup(
            jPanelSpace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelSpace6);

        jPanelSeparador1.setBackground(new java.awt.Color(51, 51, 51));
        jPanelSeparador1.setMinimumSize(new java.awt.Dimension(400, 1));
        jPanelSeparador1.setPreferredSize(new java.awt.Dimension(400, 1));

        javax.swing.GroupLayout jPanelSeparador1Layout = new javax.swing.GroupLayout(jPanelSeparador1);
        jPanelSeparador1.setLayout(jPanelSeparador1Layout);
        jPanelSeparador1Layout.setHorizontalGroup(
            jPanelSeparador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelSeparador1Layout.setVerticalGroup(
            jPanelSeparador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelSeparador1);

        jPanelSpace4.setBackground(new java.awt.Color(10, 10, 10));

        javax.swing.GroupLayout jPanelSpace4Layout = new javax.swing.GroupLayout(jPanelSpace4);
        jPanelSpace4.setLayout(jPanelSpace4Layout);
        jPanelSpace4Layout.setHorizontalGroup(
            jPanelSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelSpace4Layout.setVerticalGroup(
            jPanelSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelSpace4);

        jPanelDeveloper.setBackground(new java.awt.Color(10, 10, 10));
        jPanelDeveloper.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        jPanelDeveloper.setMaximumSize(new java.awt.Dimension(400, 140));
        jPanelDeveloper.setMinimumSize(new java.awt.Dimension(400, 140));
        jPanelDeveloper.setPreferredSize(new java.awt.Dimension(400, 140));
        jPanelDeveloper.setLayout(new javax.swing.BoxLayout(jPanelDeveloper, javax.swing.BoxLayout.Y_AXIS));

        jLabelDevLabel.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLabelDevLabel.setForeground(new java.awt.Color(160, 160, 160));
        jLabelDevLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDevLabel.setText("Desarrollador");
        jLabelDevLabel.setAlignmentX(0.5F);
        jLabelDevLabel.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabelDevLabel.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabelDevLabel.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanelDeveloper.add(jLabelDevLabel);

        jLabelStudentName.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelStudentName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStudentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStudentName.setText("Sergio Xavier Fernández Martínez");
        jLabelStudentName.setAlignmentX(0.5F);
        jLabelStudentName.setMaximumSize(new java.awt.Dimension(400, 25));
        jLabelStudentName.setMinimumSize(new java.awt.Dimension(400, 25));
        jLabelStudentName.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanelDeveloper.add(jLabelStudentName);

        jLabelCareer.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLabelCareer.setForeground(new java.awt.Color(160, 160, 160));
        jLabelCareer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCareer.setText("Ingeniería en Sistemas Computacionales");
        jLabelCareer.setAlignmentX(0.5F);
        jLabelCareer.setMaximumSize(new java.awt.Dimension(400, 20));
        jLabelCareer.setMinimumSize(new java.awt.Dimension(400, 20));
        jLabelCareer.setPreferredSize(new java.awt.Dimension(400, 20));
        jPanelDeveloper.add(jLabelCareer);

        jPanelSpace8.setBackground(new java.awt.Color(10, 10, 10));
        jPanelSpace8.setMinimumSize(new java.awt.Dimension(400, 15));

        javax.swing.GroupLayout jPanelSpace8Layout = new javax.swing.GroupLayout(jPanelSpace8);
        jPanelSpace8.setLayout(jPanelSpace8Layout);
        jPanelSpace8Layout.setHorizontalGroup(
            jPanelSpace8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelSpace8Layout.setVerticalGroup(
            jPanelSpace8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelDeveloper.add(jPanelSpace8);

        jPanelContentEmail.setBackground(new java.awt.Color(26, 26, 26));
        jPanelContentEmail.setMaximumSize(new java.awt.Dimension(400, 50));
        jPanelContentEmail.setMinimumSize(new java.awt.Dimension(400, 50));
        jPanelContentEmail.setLayout(new java.awt.CardLayout());

        jPanelEmail.setBackground(new java.awt.Color(26, 26, 26));
        jPanelEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(185, 28, 28))));
        jPanelEmail.setAlignmentX(0.0F);
        jPanelEmail.setMaximumSize(new java.awt.Dimension(200, 50));
        jPanelEmail.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanelEmail.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanelEmail.setLayout(new java.awt.BorderLayout());

        jLabelLinkEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelLinkEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLinkEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLinkEmail.setText("xavfer19@gmail.com");
        jLabelLinkEmail.setMinimumSize(new java.awt.Dimension(100, 19));
        jPanelEmail.add(jLabelLinkEmail, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 48));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelIconEmail.setBackground(new java.awt.Color(0, 0, 0));
        jLabelIconEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelIconEmail.setForeground(new java.awt.Color(185, 28, 28));
        jLabelIconEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconEmail.setText("📧");
        jPanel1.add(jLabelIconEmail, java.awt.BorderLayout.CENTER);

        jPanelEmail.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanelContentEmail.add(jPanelEmail, "card2");

        jPanelDeveloper.add(jPanelContentEmail);

        jPanelContent.add(jPanelDeveloper);

        jPanelSpace2.setBackground(new java.awt.Color(10, 10, 10));
        jPanelSpace2.setMinimumSize(new java.awt.Dimension(400, 15));
        jPanelSpace2.setPreferredSize(new java.awt.Dimension(400, 15));

        javax.swing.GroupLayout jPanelSpace2Layout = new javax.swing.GroupLayout(jPanelSpace2);
        jPanelSpace2.setLayout(jPanelSpace2Layout);
        jPanelSpace2Layout.setHorizontalGroup(
            jPanelSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelSpace2Layout.setVerticalGroup(
            jPanelSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelSpace2);

        jPanelAsesor.setBackground(new java.awt.Color(10, 10, 10));
        jPanelAsesor.setMaximumSize(new java.awt.Dimension(400, 110));
        jPanelAsesor.setMinimumSize(new java.awt.Dimension(400, 110));
        jPanelAsesor.setPreferredSize(new java.awt.Dimension(400, 110));
        jPanelAsesor.setLayout(new javax.swing.BoxLayout(jPanelAsesor, javax.swing.BoxLayout.Y_AXIS));

        jLabelAsesorLabel.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLabelAsesorLabel.setForeground(new java.awt.Color(160, 160, 160));
        jLabelAsesorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAsesorLabel.setText("Asesor");
        jLabelAsesorLabel.setAlignmentX(0.5F);
        jLabelAsesorLabel.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabelAsesorLabel.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabelAsesorLabel.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanelAsesor.add(jLabelAsesorLabel);

        jLabelStudentName1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelStudentName1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStudentName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStudentName1.setText("José Antonio Castillo Gutiérrez");
        jLabelStudentName1.setAlignmentX(0.5F);
        jLabelStudentName1.setMaximumSize(new java.awt.Dimension(400, 25));
        jLabelStudentName1.setMinimumSize(new java.awt.Dimension(400, 25));
        jLabelStudentName1.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanelAsesor.add(jLabelStudentName1);

        jPanelContent.add(jPanelAsesor);

        jPanelSpace1.setBackground(new java.awt.Color(10, 10, 10));

        javax.swing.GroupLayout jPanelSpace1Layout = new javax.swing.GroupLayout(jPanelSpace1);
        jPanelSpace1.setLayout(jPanelSpace1Layout);
        jPanelSpace1Layout.setHorizontalGroup(
            jPanelSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelSpace1Layout.setVerticalGroup(
            jPanelSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelSpace1);

        jButtonAcceso.setBackground(new java.awt.Color(185, 28, 28));
        jButtonAcceso.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonAcceso.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcceso.setText("Acceder al Sistema");
        jButtonAcceso.setAlignmentX(0.5F);
        jButtonAcceso.setBorder(null);
        jButtonAcceso.setMaximumSize(new java.awt.Dimension(300, 40));
        jButtonAcceso.setMinimumSize(new java.awt.Dimension(300, 40));
        jButtonAcceso.setPreferredSize(new java.awt.Dimension(300, 40));
        jButtonAcceso.addActionListener(this::jButtonAccesoActionPerformed);
        jPanelContent.add(jButtonAcceso);

        jPanelSpace9.setBackground(new java.awt.Color(10, 10, 10));

        javax.swing.GroupLayout jPanelSpace9Layout = new javax.swing.GroupLayout(jPanelSpace9);
        jPanelSpace9.setLayout(jPanelSpace9Layout);
        jPanelSpace9Layout.setHorizontalGroup(
            jPanelSpace9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelSpace9Layout.setVerticalGroup(
            jPanelSpace9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelSpace9);

        panelBackground.add(jPanelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccesoActionPerformed
        mainFrame mFrame = new mainFrame();
        mFrame.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        mFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAccesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameBienvenida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceso;
    private javax.swing.JLabel jLabelAsesorLabel;
    private javax.swing.JLabel jLabelCareer;
    private javax.swing.JLabel jLabelDevLabel;
    private javax.swing.JLabel jLabelIconEmail;
    private javax.swing.JLabel jLabelLinkEmail;
    private javax.swing.JLabel jLabelStudentName;
    private javax.swing.JLabel jLabelStudentName1;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAsesor;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelContentEmail;
    private javax.swing.JPanel jPanelDeveloper;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSeparador1;
    private javax.swing.JPanel jPanelSpace1;
    private javax.swing.JPanel jPanelSpace2;
    private javax.swing.JPanel jPanelSpace4;
    private javax.swing.JPanel jPanelSpace6;
    private javax.swing.JPanel jPanelSpace7;
    private javax.swing.JPanel jPanelSpace8;
    private javax.swing.JPanel jPanelSpace9;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables
}