/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.PDI;

/**
 *
 * @author XAV
 */
public class Waifu2XSettings extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Waifu2XSettings.class.getName());

    /**
     * Creates new form Waifu2XSettings
     */
    public Waifu2XSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setupListeners();
        panelTTAWarning.setVisible(false); // Inicialmente invisible
    }

    private boolean upscaleClicked = false;

    private void setupListeners() {
        checkboxTTA.addItemListener(e -> {
            panelTTAWarning.setVisible(checkboxTTA.isSelected());
            panelTTAWarning.revalidate();
            panelTTAWarning.repaint();
        });

        buttonCancel.addActionListener(e -> {
            upscaleClicked = false;
            dispose();
        });

        buttonUpscale.addActionListener(e -> {
            upscaleClicked = true;
            dispose();
        });
    }

    public boolean wasUpscaleClicked() {
        return upscaleClicked;
    }

    public int getNoiseLevel() {
        int selected = comboNoise.getSelectedIndex();
        return selected - 1; // -1, 0, 1, 2, 3
    }

    public int getScale() {
        String value = (String) comboScale.getSelectedItem();
        return Integer.parseInt(value.split("x")[0]); // Extrae el número
    }

    public boolean isTTAEnabled() {
        return checkboxTTA.isSelected();
    }

    public void setNoiseLevel(int level) {
        comboNoise.setSelectedIndex(level + 1);
    }

    public void setScale(int scale) {
        String[] scales = {"2", "4", "8", "16", "32"};
        for (int i = 0; i < scales.length; i++) {
            if (Integer.parseInt(scales[i]) == scale) {
                comboScale.setSelectedIndex(i);
                break;
            }
        }
    }

    public void setTTAEnabled(boolean enabled) {
        checkboxTTA.setSelected(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelNoiseRow = new javax.swing.JPanel();
        labelNoise = new javax.swing.JLabel();
        comboNoise = new javax.swing.JComboBox<>();
        panelScaleRow = new javax.swing.JPanel();
        labelScale = new javax.swing.JLabel();
        comboScale = new javax.swing.JComboBox<>();
        panelTTARow = new javax.swing.JPanel();
        checkboxTTA = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        panelTTAWarning = new javax.swing.JPanel();
        labelTTAWarning = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        labelTTAWarningMensaje = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        panelButtonsInner = new javax.swing.JPanel();
        buttonCancel = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        buttonUpscale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración de Upscalling");
        setMinimumSize(new java.awt.Dimension(550, 350));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(550, 350));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(10, 10, 10));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(10, 10, 10));
        panelHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        panelHeader.setMinimumSize(new java.awt.Dimension(500, 40));
        panelHeader.setPreferredSize(new java.awt.Dimension(500, 40));
        panelHeader.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(185, 28, 28));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIGURACIÓN DE UPSCALLING");
        panelHeader.add(jLabel1, java.awt.BorderLayout.CENTER);

        mainPanel.add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelContent.setBackground(new java.awt.Color(10, 10, 10));
        panelContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 5, 20));
        panelContent.setLayout(new javax.swing.BoxLayout(panelContent, javax.swing.BoxLayout.Y_AXIS));

        panelNoiseRow.setBackground(new java.awt.Color(10, 10, 10));
        panelNoiseRow.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelNoiseRow.setMaximumSize(new java.awt.Dimension(500, 50));
        panelNoiseRow.setPreferredSize(new java.awt.Dimension(500, 50));
        panelNoiseRow.setLayout(new java.awt.BorderLayout());

        labelNoise.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelNoise.setForeground(new java.awt.Color(185, 28, 28));
        labelNoise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNoise.setText("Nivel de Ruido:");
        labelNoise.setPreferredSize(new java.awt.Dimension(150, 35));
        panelNoiseRow.add(labelNoise, java.awt.BorderLayout.LINE_START);

        comboNoise.setBackground(new java.awt.Color(37, 37, 37));
        comboNoise.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        comboNoise.setForeground(new java.awt.Color(255, 255, 255));
        comboNoise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "−1 (Ninguno)", "0 (Debil)", "1 (Normal)", "2 (Fuerte)", "3 (Máximo)" }));
        comboNoise.setToolTipText("Selecciona el nivel de eliminación de ruido. Mayor nivel, mejor limpieza pero más tiempo.");
        comboNoise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboNoise.setPreferredSize(new java.awt.Dimension(200, 35));
        panelNoiseRow.add(comboNoise, java.awt.BorderLayout.CENTER);

        panelContent.add(panelNoiseRow);

        panelScaleRow.setBackground(new java.awt.Color(10, 10, 10));
        panelScaleRow.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelScaleRow.setMaximumSize(new java.awt.Dimension(500, 50));
        panelScaleRow.setPreferredSize(new java.awt.Dimension(500, 50));
        panelScaleRow.setLayout(new java.awt.BorderLayout());

        labelScale.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelScale.setForeground(new java.awt.Color(185, 28, 28));
        labelScale.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelScale.setText("Nivel de Escalado:");
        labelScale.setPreferredSize(new java.awt.Dimension(150, 35));
        panelScaleRow.add(labelScale, java.awt.BorderLayout.LINE_START);

        comboScale.setBackground(new java.awt.Color(37, 37, 37));
        comboScale.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        comboScale.setForeground(new java.awt.Color(255, 255, 255));
        comboScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2x (200%)", "4x (400%)", "8x (800%)", "16x (1600%)", "32x (3200%)" }));
        comboScale.setToolTipText("Selecciona el multiplicador de tamaño. Mayor escala = imagen más grande pero más tiempo.");
        comboScale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboScale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboScale.setPreferredSize(new java.awt.Dimension(200, 35));
        panelScaleRow.add(comboScale, java.awt.BorderLayout.CENTER);

        panelContent.add(panelScaleRow);

        panelTTARow.setBackground(new java.awt.Color(10, 10, 10));
        panelTTARow.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelTTARow.setMaximumSize(new java.awt.Dimension(500, 100));
        panelTTARow.setPreferredSize(new java.awt.Dimension(500, 50));
        panelTTARow.setLayout(new javax.swing.BoxLayout(panelTTARow, javax.swing.BoxLayout.X_AXIS));

        checkboxTTA.setBackground(new java.awt.Color(10, 10, 10));
        checkboxTTA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkboxTTA.setForeground(new java.awt.Color(255, 255, 255));
        checkboxTTA.setText("TTA - Mejorar Calidad");
        checkboxTTA.setToolTipText("Test-Time Augmentation: mejora significativa la calidad pero triplica el tiempo de procesamiento.");
        checkboxTTA.setAlignmentX(0.5F);
        panelTTARow.add(checkboxTTA);
        panelTTARow.add(filler1);

        panelTTAWarning.setBackground(new java.awt.Color(26, 26, 26));
        panelTTAWarning.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 28, 28)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        panelTTAWarning.setMaximumSize(new java.awt.Dimension(286, 70));
        panelTTAWarning.setMinimumSize(new java.awt.Dimension(286, 70));
        panelTTAWarning.setLayout(new javax.swing.BoxLayout(panelTTAWarning, javax.swing.BoxLayout.Y_AXIS));

        labelTTAWarning.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelTTAWarning.setForeground(new java.awt.Color(255, 200, 0));
        labelTTAWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTTAWarning.setText("ADVERTENCIA");
        labelTTAWarning.setMaximumSize(new java.awt.Dimension(276, 25));
        labelTTAWarning.setPreferredSize(new java.awt.Dimension(276, 25));
        panelTTAWarning.add(labelTTAWarning);
        panelTTAWarning.add(filler2);

        labelTTAWarningMensaje.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelTTAWarningMensaje.setForeground(new java.awt.Color(255, 200, 0));
        labelTTAWarningMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTTAWarningMensaje.setText("TTA Mode triplicará el tiempo de procesamiento.");
        labelTTAWarningMensaje.setMaximumSize(new java.awt.Dimension(276, 25));
        labelTTAWarningMensaje.setPreferredSize(new java.awt.Dimension(276, 25));
        panelTTAWarning.add(labelTTAWarningMensaje);

        panelTTARow.add(panelTTAWarning);

        panelContent.add(panelTTARow);

        mainPanel.add(panelContent, java.awt.BorderLayout.CENTER);

        panelButtons.setBackground(new java.awt.Color(10, 10, 10));
        panelButtons.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(51, 51, 51)));
        panelButtons.setPreferredSize(new java.awt.Dimension(500, 60));
        panelButtons.setLayout(new java.awt.BorderLayout());

        panelButtonsInner.setBackground(new java.awt.Color(10, 10, 10));
        panelButtonsInner.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        panelButtonsInner.setLayout(new javax.swing.BoxLayout(panelButtonsInner, javax.swing.BoxLayout.X_AXIS));

        buttonCancel.setBackground(new java.awt.Color(37, 37, 37));
        buttonCancel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancel.setText("CANCELAR");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        buttonCancel.setFocusPainted(false);
        buttonCancel.setMaximumSize(new java.awt.Dimension(100, 35));
        buttonCancel.setPreferredSize(new java.awt.Dimension(100, 35));
        panelButtonsInner.add(buttonCancel);
        panelButtonsInner.add(filler3);

        buttonUpscale.setBackground(new java.awt.Color(185, 28, 28));
        buttonUpscale.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonUpscale.setForeground(new java.awt.Color(255, 255, 255));
        buttonUpscale.setText("UPSCALE");
        buttonUpscale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 28, 28)));
        buttonUpscale.setFocusPainted(false);
        buttonUpscale.setMaximumSize(new java.awt.Dimension(100, 35));
        buttonUpscale.setPreferredSize(new java.awt.Dimension(100, 35));
        panelButtonsInner.add(buttonUpscale);

        panelButtons.add(panelButtonsInner, java.awt.BorderLayout.CENTER);

        mainPanel.add(panelButtons, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Waifu2XSettings dialog = new Waifu2XSettings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonUpscale;
    private javax.swing.JCheckBox checkboxTTA;
    private javax.swing.JComboBox<String> comboNoise;
    private javax.swing.JComboBox<String> comboScale;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNoise;
    private javax.swing.JLabel labelScale;
    private javax.swing.JLabel labelTTAWarning;
    private javax.swing.JLabel labelTTAWarningMensaje;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelButtonsInner;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelNoiseRow;
    private javax.swing.JPanel panelScaleRow;
    private javax.swing.JPanel panelTTARow;
    private javax.swing.JPanel panelTTAWarning;
    // End of variables declaration//GEN-END:variables
}
