/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.PDI;

/**
 *
 * @author x4vier19
 */
public class Waifu2XProgressDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Waifu2XProgressDialog.class.getName());

    private long startTime;
    private javax.swing.Timer updateTimer;

    /**
     * Creates new form Waifu2XProgressDialog
     */
    public Waifu2XProgressDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        startTime = System.currentTimeMillis();
        setupTimer();
    }

    private void setupTimer() {
        updateTimer = new javax.swing.Timer(500, e -> updateTimeLabel());
        updateTimer.start();
    }

    private void updateTimeLabel() {
        long elapsed = (System.currentTimeMillis() - startTime) / 1000;
        if (elapsed < 60) {
            labelTimeValue.setText(elapsed + "s");
        } else {
            long minutes = elapsed / 60;
            long seconds = elapsed % 60;
            labelTimeValue.setText(String.format("%dm %ds", minutes, seconds));
        }
    }

    public void close() {
        if (updateTimer != null) {
            updateTimer.stop();
        }
        dispose();
    }

    public void setProcessingMessage(String message) {
        labelProcessing.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        labelProcessing = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        progressBar = new javax.swing.JProgressBar();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        panelTime = new javax.swing.JPanel();
        labelTimeLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        labelTimeValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procesando con Waifu2X");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(500, 240));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(10, 10, 10));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(500, 240));
        mainPanel.setMinimumSize(new java.awt.Dimension(500, 240));
        mainPanel.setPreferredSize(new java.awt.Dimension(500, 240));
        mainPanel.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(10, 10, 10));
        panelHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        panelHeader.setMinimumSize(new java.awt.Dimension(100, 50));
        panelHeader.setPreferredSize(new java.awt.Dimension(100, 50));
        panelHeader.setLayout(new java.awt.BorderLayout());

        labelTitle.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(185, 28, 28));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("PROCESANDO CON WAIFU2X");
        panelHeader.add(labelTitle, java.awt.BorderLayout.CENTER);

        mainPanel.add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelContent.setBackground(new java.awt.Color(10, 10, 10));
        panelContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelContent.setLayout(new javax.swing.BoxLayout(panelContent, javax.swing.BoxLayout.Y_AXIS));

        labelProcessing.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelProcessing.setForeground(new java.awt.Color(255, 255, 255));
        labelProcessing.setText("Procesando imagen... ");
        panelContent.add(labelProcessing);
        panelContent.add(filler1);

        progressBar.setBackground(new java.awt.Color(37, 37, 37));
        progressBar.setForeground(new java.awt.Color(185, 28, 28));
        progressBar.setAlignmentX(0.0F);
        progressBar.setIndeterminate(true);
        progressBar.setMaximumSize(new java.awt.Dimension(32767, 25));
        progressBar.setPreferredSize(new java.awt.Dimension(460, 25));
        panelContent.add(progressBar);
        panelContent.add(filler2);

        panelTime.setBackground(new java.awt.Color(10, 10, 10));
        panelTime.setAlignmentX(0.0F);
        panelTime.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        panelTime.setLayout(new javax.swing.BoxLayout(panelTime, javax.swing.BoxLayout.X_AXIS));

        labelTimeLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTimeLabel.setForeground(new java.awt.Color(160, 160, 160));
        labelTimeLabel.setText("Tiempo:");
        panelTime.add(labelTimeLabel);
        panelTime.add(filler3);

        labelTimeValue.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTimeValue.setForeground(new java.awt.Color(185, 28, 28));
        labelTimeValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTimeValue.setText("0s");
        panelTime.add(labelTimeValue);

        panelContent.add(panelTime);

        mainPanel.add(panelContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Waifu2XProgressDialog dialog = new Waifu2XProgressDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel labelProcessing;
    private javax.swing.JLabel labelTimeLabel;
    private javax.swing.JLabel labelTimeValue;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelTime;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
